version: '2.0'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - common

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - common

volumes:
  postgres:

networks:
  common:
    external: true
