version: '2.0'
services:
  nginx:
    build:
      context: nginx
    hostname: nginx
    container_name: nginx
    restart: always
    depends_on:
      - phpmyadmin
      - phppgadmin
    networks:
      - common
    ports:
      - "80:80"

  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - common

  phppgadmin:
    image: dockage/phppgadmin
    hostname: phppgadmin
    container_name: phppgadmin
    environment:
      PHP_PG_ADMIN_SERVER_DESC: postgres
      PHP_PG_ADMIN_SERVER_HOST: postgres
      PHP_PG_ADMIN_LEFT_WIDTH: 280
      PHP_PG_ADMIN_THEME: cappuccino
    depends_on:
      - postgres
    networks:
      - common

  mysql:
    image: mysql:5.5
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - common
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    hostname: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: 1234
    networks:
      - common

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - common

volumes:
  postgres:
  mysql:

networks:
  common:
    external: true
