version: '2.0'
services:
    nginx:
        build:
            context: nginx
        hostname: nginx
        container_name: nginx
        restart: always
        networks:
            - common
        ports:
            - "80:80"

    postgres:
        image: postgres
        hostname: postgres
        container_name: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: 1234
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - common

    mysql:
        image: mysql:5.5
        container_name: mysql
        hostname: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1234
        networks:
            - common
        ports:
            - "3306:3306"
        volumes:
            - mysql:/var/lib/mysql

    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        hostname: mailhog
        restart: always
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - common

volumes:
    postgres:
    mysql:

networks:
    common:
        external: true
